### ISSUE TITLE
Help to resolve error

### ISSUE THREAD

**Issue by Trooper-Pankaj** [freedomwebtech/yolov10-plants-counting#2]
**I followed the instructions ditto without any exception, however,**

when I run this cell
%cd {HOME}

!yolo task=detect mode=train model=[yolov10s.pt](javascript:void(0);) data=/content/datasets/freedomtech/data.yaml epochs=100 imgsz=800 plots=True

**I get following error**

Starting training for 100 epochs...

      Epoch    GPU_mem     box_om     cls_om     dfl_om     box_oo     cls_oo     dfl_oo  Instances       Size
  0% 0/7 [[00:00](https://www.youtube.com/watch?v=rjs0YY5lPGA)<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 594, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/[model.py](javascript:void(0);)", line 657, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/[trainer.py](javascript:void(0);)", line 213, in train
    self._do_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/[trainer.py](javascript:void(0);)", line 363, in _do_train
    for i, batch in pbar:
  File "/usr/local/lib/python3.10/dist-packages/tqdm/[std.py](javascript:void(0);)", line 1181, in _iter_
    for obj in iterable:
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/[build.py](javascript:void(0);)", line 49, in _iter_
    yield next(self.iterator)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/[dataloader.py](javascript:void(0);)", line 630, in _next_
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/[dataloader.py](javascript:void(0);)", line 1344, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/[dataloader.py](javascript:void(0);)", line 1370, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_[utils.py](javascript:void(0);)", line 706, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/[worker.py](javascript:void(0);)", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/[fetch.py](javascript:void(0);)", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/[fetch.py](javascript:void(0);)", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/[base.py](javascript:void(0);)", line 253, in _getitem_
    return self.transforms(self.get_image_and_label(index))
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/[augment.py](javascript:void(0);)", line 74, in _call_
    data = t(data)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/[augment.py](javascript:void(0);)", line 866, in _call_
    new = self.transform(image=im, bboxes=bboxes, class_labels=cls)  # transformed
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/[composition.py](javascript:void(0);)", line 334, in _call_
    self.preprocess(data)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/[composition.py](javascript:void(0);)", line 368, in preprocess
    p.preprocess(data)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/[utils.py](javascript:void(0);)", line 125, in preprocess
    data = self.add_label_fields_to_data(data)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/[utils.py](javascript:void(0);)", line 185, in add_label_fields_to_data
    encoded_labels = encoder.fit_transform(data[label_field])
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/[utils.py](javascript:void(0);)", line 60, in fit_transform
    self.fit(y)
  File "/usr/local/lib/python3.10/dist-packages/albumentations/core/[utils.py](javascript:void(0);)", line 48, in fit
    unique_labels = sorted(set(y))
TypeError: unhashable type: 'numpy.ndarray'

**please help**

**Comment by freedomwebtech** [comment]
change imgsz=640

**Comment by Trooper-Pankaj** [comment]
**it did not resolve the issue**, I get same error. Please look into the matter.

**Comment by Trooper-Pankaj** [comment]
I tried with imgsz=640 but the error remains, please help resolve the issue.





Col Pankaj Sharma+919899227179 

    On Thursday 26 September, 2024 at 01:51:40 pm IST, freedomwebtech ***@***.***> wrote:  
 
 

change imgsz=640

**Comment by Trooper-Pankaj** [comment]
Please Help in resolving above issue

**Comment by Trooper-Pankaj** [comment]
Thanks a lot
